baseURL: http://blog.pengyuc.com/
languageCode: en-us
title: Blog | Peng-Yu Chen
theme: hugo-blog-awesome

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics: '' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji: true

# set markup.highlight.noClasses = false to enable code highlight
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - pageRef: /
      name: Home
      url: /
      weight: 10
    - pageRef: posts
      name: Posts
      url: /posts/
      weight: 20
    - pageRef: about
      name: About
      url: /about/
      weight: 30

params:
  sitename: Blog | Peng-Yu Chen
  defaultColor: light # set default color mode: dark or light
  # description: Blog
  author:
    # Put the file in assets/avatar.jpg. Also make sure that image has same
    # height and width.
    avatar: avatar.jpg
    intro: Tech and Learning Blog
    name: Peng-Yu Chen
    description: A blog about my learnings in technology and collection of my thoughts.
  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/pengyuc'
    - name: github
      url: 'https://github.com/walkccc'
